const test = require('node:test');
const assert = require('node:assert/strict');
const React = require('react');
const ReactDOMServer = require('react-dom/server');
const { loadModule } = require('./helpers/moduleLoader');

function Link({ href, children, ...props }) {
  return React.createElement('a', { href, ...props }, children);
}

function Image({ src, alt, width, height, ...props }) {
  return React.createElement('img', { src, alt, width, height, ...props });
}

function createPageMocks(extra = {}) {
  return {
    'next/link': Link,
    'next/image': Image,
    'next/navigation': { useRouter: () => ({ push: () => {} }) },
    axios: { post: async () => ({ data: {} }) },
    'react-hot-toast': { success: () => {}, error: () => {}, toast: { error: () => {} } },
    'next/font/google': { Inter: () => ({ className: 'inter-test-class' }) },
    ...extra
  };
}

function loadDefault(relativePath, mocks = createPageMocks()) {
  return loadModule(relativePath, { mocks }).default;
}

function render(element) {
  return ReactDOMServer.renderToStaticMarkup(element);
}

test('root layout exports the default metadata used by the application', () => {
  const layoutModule = loadModule('src/app/layout.tsx', { mocks: createPageMocks() });

  assert.equal(layoutModule.metadata.title, 'Create Next App');
  assert.equal(layoutModule.metadata.description, 'Generated by create next app');
});

test('root layout renders an English document with the configured font class', () => {
  const RootLayout = loadDefault('src/app/layout.tsx');
  const html = render(React.createElement(RootLayout, { children: React.createElement('main', null, 'Child content') }));

  assert.match(html, /<html[^>]*lang="en"/);
  assert.match(html, /<body[^>]*class="inter-test-class"/);
  assert.ok(html.includes('Child content'));
});

test('home page renders the starter editing guidance', () => {
  const Home = loadDefault('src/app/page.tsx');
  const html = render(React.createElement(Home));

  assert.ok(html.includes('Get started by editing'));
  assert.ok(html.includes('src/app/page.tsx'));
});

test('home page renders all four starter resource sections', () => {
  const Home = loadDefault('src/app/page.tsx');
  const html = render(React.createElement(Home));

  for (const heading of ['Docs', 'Learn', 'Templates', 'Deploy']) {
    assert.ok(html.includes(heading), `expected ${heading} to be present`);
  }
});

test('home page exposes the expected external resource links', () => {
  const Home = loadDefault('src/app/page.tsx');
  const html = render(React.createElement(Home));

  assert.ok(html.includes('https://nextjs.org/docs'));
  assert.ok(html.includes('https://nextjs.org/learn'));
  assert.ok(html.includes('https://vercel.com/templates'));
  assert.ok(html.includes('https://vercel.com/new'));
});

test('home page renders accessible image alt text', () => {
  const Home = loadDefault('src/app/page.tsx');
  const html = render(React.createElement(Home));

  assert.ok(html.includes('alt="Next.js Logo"'));
  assert.ok(html.includes('alt="Vercel Logo"'));
});

test('profile page renders the generic profile content', () => {
  const ProfilePage = loadDefault('src/app/profile/page.tsx');
  const html = render(React.createElement(ProfilePage));

  assert.ok(html.includes('<h1>Profile</h1>'));
  assert.ok(html.includes('Profile Page'));
});

test('dynamic profile page includes the requested profile id', () => {
  const UserProfile = loadDefault('src/app/profile/[id]/page.tsx');
  const html = render(React.createElement(UserProfile, { params: { id: 'abc-123' } }));

  assert.ok(html.includes('<h1>Profile</h1>'));
  assert.ok(html.includes('abc-123'));
});

test('login page renders form fields and navigation to signup', () => {
  const LoginPage = loadDefault('src/app/login/page.tsx');
  const html = render(React.createElement(LoginPage));

  assert.ok(html.includes('Login'));
  assert.ok(html.includes('for="email"'));
  assert.ok(html.includes('for="password"'));
  assert.ok(html.includes('Login here'));
  assert.ok(html.includes('href="/signup"'));
});

test('signup page renders form fields and navigation to login', () => {
  const SignupPage = loadDefault('src/app/signup/page.tsx');
  const html = render(React.createElement(SignupPage));

  assert.ok(html.includes('Signup'));
  assert.ok(html.includes('for="username"'));
  assert.ok(html.includes('for="email"'));
  assert.ok(html.includes('for="password"'));
  assert.ok(html.includes('Signup Here'));
  assert.ok(html.includes('href="/login"'));
});
