const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const React = require('react');
const ReactDOMServer = require('react-dom/server');
const { loadSource } = require('./helpers/loadSource');

function render(element) {
  return ReactDOMServer.renderToStaticMarkup(element);
}

function componentMocks() {
  return {
    'next/image': function MockImage({ priority, ...props }) {
      return React.createElement('img', props);
    },
    'next/link': function MockLink({ href, children, ...props }) {
      return React.createElement('a', { href, ...props }, children);
    },
    'next/navigation': {
      useRouter() {
        return { push() {} };
      },
    },
    'next/font/google': {
      Inter() {
        return { className: 'mock-inter-class' };
      },
    },
    axios: { post: async () => ({ data: {} }) },
    'react-hot-toast': { success() {}, error() {}, toast: { error() {}, success() {} } },
  };
}

function loadDefault(relativePath) {
  const mod = loadSource(relativePath, componentMocks());
  return mod.default || mod;
}

describe('app pages and layout rendering', () => {
  it('renders the home page getting-started instruction', () => {
    const Home = loadDefault('src/app/page.tsx');
    const html = render(React.createElement(Home));

    assert.match(html, /Get started by editing/);
    assert.match(html, /src\/app\/page\.tsx/);
  });

  it('renders all four default home page resource cards', () => {
    const Home = loadDefault('src/app/page.tsx');
    const html = render(React.createElement(Home));

    for (const label of ['Docs', 'Learn', 'Templates', 'Deploy']) {
      assert.match(html, new RegExp(label));
    }
  });

  it('renders expected image alt text on the home page', () => {
    const Home = loadDefault('src/app/page.tsx');
    const html = render(React.createElement(Home));

    assert.match(html, /alt="Vercel Logo"/);
    assert.match(html, /alt="Next\.js Logo"/);
  });

  it('exposes the default metadata values from the root layout module', () => {
    const layoutModule = loadSource('src/app/layout.tsx', componentMocks());

    assert.deepEqual(layoutModule.metadata, {
      title: 'Create Next App',
      description: 'Generated by create next app',
    });
  });

  it('renders the root layout with the html language and body class', () => {
    const layoutModule = loadSource('src/app/layout.tsx', componentMocks());
    const RootLayout = layoutModule.default;
    const html = render(React.createElement(RootLayout, null, React.createElement('main', null, 'Child content')));

    assert.match(html, /<html lang="en">/);
    assert.match(html, /<body class="mock-inter-class">/);
    assert.match(html, /Child content/);
  });

  it('renders the profile landing page content', () => {
    const ProfilePage = loadDefault('src/app/profile/page.tsx');
    const html = render(React.createElement(ProfilePage));

    assert.match(html, /<h1>Profile<\/h1>/);
    assert.match(html, /Profile Page/);
  });

  it('renders a dynamic profile id in the profile detail page', () => {
    const UserProfile = loadDefault('src/app/profile/[id]/page.tsx');
    const html = render(React.createElement(UserProfile, { params: { id: 'user-123' } }));

    assert.match(html, /Profile Page of user-123/);
  });

  it('renders the login form with empty inputs and a signup link', () => {
    const LoginPage = loadDefault('src/app/login/page.tsx');
    const html = render(React.createElement(LoginPage));

    assert.match(html, /<h1>Login<\/h1>/);
    assert.match(html, /id="email"/);
    assert.match(html, /id="password"/);
    assert.match(html, /Login here/);
    assert.match(html, /href="\/signup"/);
  });

  it('renders the signup form with all fields and a login link', () => {
    const SignupPage = loadDefault('src/app/signup/page.tsx');
    const html = render(React.createElement(SignupPage));

    assert.match(html, /<h1>Signup<\/h1>/);
    assert.match(html, /id="username"/);
    assert.match(html, /id="email"/);
    assert.match(html, /id="password"/);
    assert.match(html, /Signup Here/);
    assert.match(html, /href="\/login"/);
  });
});
